services:
  migrator:
    image: ghcr.io/nomfodm/beacon:latest
    env_file: .env
    environment:
      DATABASE__URL: postgresql+asyncpg://postgres:pass@postgres:5432/infinity
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app:
    image: ghcr.io/nomfodm/beacon:latest
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE__URL: postgresql+asyncpg://postgres:pass@postgres:5432/infinity
      REDIS__HOST: redis
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: infinity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d infinity"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
